1

diff --git a/.github/workflows/release-grimoirelab-component.yml b/.github/workflows/release-grimoirelab-component.yml
--- a/.github/workflows/release-grimoirelab-component.yml
+++ b/.github/workflows/release-grimoirelab-component.yml
@@ -11,10 +11,15 @@ on:
         description: 'Git config name'
         type: string
         required: true
-      release_candidate:
-        description: 'Create a release candidate version'
+      prerelease:
+        description: 'Create a prerelease version'
         type: string
         required: true
+      prerelease_label:
+        description: 'Label for the prerelease version'
+        type: string
+        required: false
+        default: 'rc'
       bump_major:
         description: 'Create a new major version release'
         type: string
@@ -64,10 +69,10 @@ jobs:
     steps:
       - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
 
-      - name: Set up Python 3.11
+      - name: Set up Python
         uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
         with:
-          python-version: 3.11
+          python-version: 3.12
 
       - name: Set up Git config
         run: |
@@ -84,10 +89,9 @@ jobs:
           cd ${{ inputs.module_directory }}
           git checkout main
 
-      - name: Install poetry
+      - name: Install Poetry
         run: |
-          curl -sSL https://install.python-poetry.org | python3 -
-          echo "PATH=$HOME/.poetry/bin:$PATH" >> $GITHUB_ENV
+          pipx install poetry
         shell: bash
 
       - name: Install release-tools
@@ -101,29 +105,29 @@ jobs:
           echo "version=$version" >> $GITHUB_OUTPUT
         working-directory: ${{ inputs.module_directory }}
 
-      - id: check-dependencies
-        name: Check is package dependencies are ready
-        run: |
-          dependencies="${{ inputs.dependencies }}"
-          if [ ! -z "$dependencies" ]
-          then
-            clear_cache() {
-              for cache in $(poetry cache list); do
-                echo "Clear $cache"
-                poetry -n cache clear $cache --all
-              done
-            }
-            timeout=5
-            for i in $(seq 5)
-            do
-              clear_cache
-              poetry add --lock --dry-run $dependencies && exit 0
-              sleep $timeout
-              timeout=$(( timeout * 2 ))
-            done
-            exit 1
-          fi
-        working-directory: ${{ inputs.module_directory }}
+#      - id: check-dependencies
+#        name: Check is package dependencies are ready
+#        run: |
+#          dependencies="${{ inputs.dependencies }}"
+#          if [ ! -z "$dependencies" ]
+#          then
+#            clear_cache() {
+#              for cache in $(poetry cache list); do
+#                echo "Clear $cache"
+#                poetry -n cache clear $cache --all
+#              done
+#            }
+#            timeout=5
+#            for i in $(seq 5)
+#            do
+#              clear_cache
+#              poetry add --lock --dry-run $dependencies && exit 0
+#              sleep $timeout
+#              timeout=$(( timeout * 2 ))
+#            done
+#            exit 1
+#          fi
+#        working-directory: ${{ inputs.module_directory }}
 
       - id: update-dependencies
         name: Update package dependencies
@@ -144,9 +148,9 @@ jobs:
         continue-on-error: true
         shell: bash {0}
         run: |
-          if [ ${{ inputs.release_candidate }} == 'true' ]
+          if [ ${{ inputs.prerelease }} == 'true' ]
           then
-            rcArg='--pre-release'
+            rcArg='--pre-release --pre-release-label ${{ inputs.prerelease_label }}'
           else
             rcArg=''
           fi
@@ -165,9 +169,9 @@ jobs:
             echo "Dependencies updated, force new version"
             version=$(semverup --bump-version patch $rcArg)
             echo "forced_version=true" >> $GITHUB_OUTPUT
-          elif [ -z $version ] && [ ${{ inputs.release_candidate }} != 'true' ] && [[ "$old_version" =~ .*rc.* ]]
+          elif [ -z $version ] && [ ${{ inputs.prerelease }} != 'true' ] && [[ "$old_version" =~ (alpha|beta|rc) ]]
           then
-            echo "Create final version from rc"
+            echo "Create final version from pre-release"
             version=$(semverup --bump-version patch)
             echo "forced_version=true" >> $GITHUB_OUTPUT
           else
@@ -194,7 +198,7 @@ jobs:
           version=${{ steps.version.outputs.version }}
           eof="EOF$(date +%s)"
           release_file="releases/$version.md"
-          if [ ${{ inputs.release_candidate }} == 'true' ]
+          if [ ${{ inputs.prerelease }} == 'true' ]
           then
             newsArg=''
             rcArg='--pre-release'
@@ -214,8 +218,8 @@ jobs:
             
             * Update Poetry's package dependencies
           EOF
-            # Update NEWS file if it is not a release candidate
-            if [ ${{ inputs.release_candidate }} != 'true' ]
+            # Update NEWS file if it is not a pre-release
+            if [ ${{ inputs.prerelease }} != 'true' ]
             then
               mv NEWS old_NEWS
               echo -e "# Releases\n" >> NEWS
@@ -242,7 +246,7 @@ jobs:
         name: Publish new version.
         if: steps.semverup.outcome == 'success'
         run: |
-          if [ ${{ inputs.release_candidate }} == 'true' ]
+          if [ ${{ inputs.prerelease }} == 'true' ]
           then
             publish ${{ steps.version.outputs.version }} "${{ inputs.git_name }} <${{ inputs.git_email }}>" --push origin --remote-branch main --no-cleanup
           else
@@ -283,35 +287,35 @@ jobs:
             fi
           done
 
-      - id: check-package-ready
-        name: Wait for package ready in PyPI
-        shell: bash
-        if: steps.wait-for-release.outcome == 'success'
-        run: |
-          package="${{ inputs.module_name }}"
-          version="${{ steps.version.outputs.version }}"
-          # Format version 1.2.3-rc.1 to 1.2.3rc1
-          versionNum=${version%-*}
-          versionRC=${version#$versionNum}
-          versionRC=${versionRC//[-.]/}
-          currentVersion="${versionNum}${versionRC}"
-
-          pip install --upgrade pip
-          for i in $(seq 20)
-          do
-            pip index versions --pre $package > pip_versions.txt
-            pipVersion=$(cat pip_versions.txt | head -n 1 | cut -f2 -d '(' | cut -f1 -d ')')
-            echo "$currentVersion $pipVersion"
-            if [ "$pipVersion" = "$currentVersion" ]
-            then
-              echo "Same version"
-              exit 0
-            fi
-            echo "Wait for PyPI..."
-            sleep 10
-          done
-          echo "Latest version doesn't match after several retries"
-          exit 1
+#      - id: check-package-ready
+#        name: Wait for package ready in PyPI
+#        shell: bash
+#        if: steps.wait-for-release.outcome == 'success'
+#        run: |
+#          package="${{ inputs.module_name }}"
+#          version="${{ steps.version.outputs.version }}"
+#          # Format version 1.2.3-rc.1 to 1.2.3rc1
+#          versionNum=${version%-*}
+#          versionRC=${version#$versionNum}
+#          versionRC=${versionRC//[-.]/}
+#          currentVersion="${versionNum}${versionRC}"
+#
+#          pip install --upgrade pip
+#          for i in $(seq 20)
+#          do
+#            pip index versions --pre $package > pip_versions.txt
+#            pipVersion=$(cat pip_versions.txt | head -n 1 | cut -f2 -d '(' | cut -f1 -d ')')
+#            echo "$currentVersion $pipVersion"
+#            if [ "$pipVersion" = "$currentVersion" ]
+#            then
+#              echo "Same version"
+#              exit 0
+#            fi
+#            echo "Wait for PyPI..."
+#            sleep 10
+#          done
+#          echo "Latest version doesn't match after several retries"
+#          exit 1
 
       - id: rollback
         name: Rollback last commit and remove tag
